version: '3'

services:
  www:
    build: './src/www'
    restart: always
    volumes:
      - './src/www:/app'
    ports:
      - '8080:80'
  api:
    build: './src/api'
    restart: always
    volumes:
      - './src/api:/app'
    ports:
      - '8000:80'
